### ISSUE TITLE
Calling broker.shutdown or subscription.cancel waits indefinitely if connection is not healthy

### ISSUE THREAD

**Issue by satazor** [guidesmiths/rascal#126] opened 2020-09-01 22:30 UTC
If connection to RabbitMQ is lost (reconnecting), calling `broker.shutdown()` or any of the `subscription.cancel()` waits indefinitely if connection is not healthy.

I've discovered this issue in a k8s environment. Basically the readiness probe of a service reported failure because the RabbitMQ connection is lost. After some time, k8s will restart the service, sending a SIGTERM signal. I am handling this signal to dispose resources, including shutting down the broker, but it hangs.

**Comment by cressie176** [comment] 2020-09-22 16:10
Hi @satazor,

Just letting you know I haven't forgotten about this issue. Sorry it's taking so long.

**Comment by andreypetruk1** [comment] 2020-12-03 16:43
Hi there. Any news about this issue? Maybe there is some workarounds?

**Comment by cressie176** [comment] 2020-12-06 23:17
No updates @andreypetruk1

**Comment by cressie176** [comment] 2021-01-02 15:47
I've just pushed what I hope is a fix for this. I was able to reproduce and solve the problem locally at least.

The approach I've taken is to "forewarn" each of the vhosts when broker.shutdown is called, but before the subscriptions are cancelled. When forewarned, a vhost will resume subscriber channel operations, but instead of returning a channel, it yields nothing. When the subscriber does not receive a channel, it assumes the vhost is shutting down and becomes dormant.

Because the subscriber channel operations have been resumed, the broker is able to cancel any remaining subscriptions, and continue with the shutdown. By default rascal is configured to wait 10 seconds for inflight messages to be acknowledged before the channels are properly closed. If this exceeds your kubernetes timeout you may run into a different issue, but you can adjust this setting using the deferCloseChannel subscription options.

**Comment by cressie176** [comment] 2021-01-02 15:57
Published as rascal@12.0.1

Thanks for your patience and sorry it took so long. Please update/close the issue if/when you have the opportunity to re-test.

**Comment by cressie176** [comment] 2021-01-14 08:40
@satazor,

I know it's been a long time since you reported this and circumstances might of changed. Is it likely you will be able to confirm the fix solves the problem? No worries if not, but if that's the case I might as well close it now.

Thanks

**Closed** 2021-01-25 08:17 UTC

**Comment by franrojasdev** [comment] 2025-08-10 03:15
I reproduce this issue in version 14.4.5.

I have a nodejs loopback4 application, and I are working on handle gracefully shutdown... and... the `broker.shutdown()` never ends...

I have a local docker rabbitmq running: _(the env file is just my user/pass to test server)_
`docker run --env-file rabbitmq.env --name rabbitmq -d --rm -p 5672:5672 -p 15672:15672 rabbitmq:3.8.3-management-alpine`

I test my service, with some publishes and subscriptions working perfect, and a some random time i send a SIGTERM, that triggers broker.shutdown() and never ends.

NOTE: I do not reproduce the error all times, sometimes justs shutdowns in 5ms and OK, this ussualy occurs when mi service does not have rabbitmq activity, just create subscriptions on startup, and then kill the process, with no activity always shutdowns OK

I do not found connection errors in the logs of the rabbitmq server docker container

I will paste the full logs of the local container from start:

2025-08-10 03:05:47.793 [info] <0.9.0> Feature flags: list of feature flags found:
2025-08-10 03:05:47.793 [info] <0.9.0> Feature flags:   [ ] drop_unroutable_metric
2025-08-10 03:05:47.793 [info] <0.9.0> Feature flags:   [ ] empty_basic_get_metric
2025-08-10 03:05:47.793 [info] <0.9.0> Feature flags:   [ ] implicit_default_bindings
2025-08-10 03:05:47.793 [info] <0.9.0> Feature flags:   [ ] quorum_queue
2025-08-10 03:05:47.793 [info] <0.9.0> Feature flags:   [ ] virtual_host_metadata
2025-08-10 03:05:47.793 [info] <0.9.0> Feature flags: feature flag states written to disk: yes
2025-08-10 03:05:47.813 [info] <0.269.0> ra: meta data store initialised. 0 record(s) recovered
2025-08-10 03:05:47.813 [info] <0.274.0> WAL: recovering []
2025-08-10 03:05:47.815 [info] <0.278.0> 
 Starting RabbitMQ 3.8.3 on Erlang 22.3.4.1
 Copyright (c) 2007-2020 Pivotal Software, Inc.
 Licensed under the MPL 1.1. Website: https://rabbitmq.com

  ##  ##      RabbitMQ 3.8.3
  ##  ##
  ##########  Copyright (c) 2007-2020 Pivotal Software, Inc.
  ######  ##
  ##########  Licensed under the MPL 1.1. Website: https://rabbitmq.com

  Doc guides: https://rabbitmq.com/documentation.html
  Support:    https://rabbitmq.com/contact.html
  Tutorials:  https://rabbitmq.com/getstarted.html
  Monitoring: https://rabbitmq.com/monitoring.html

  Logs: <stdout>

  Config file(s): /etc/rabbitmq/rabbitmq.conf

  Starting broker...2025-08-10 03:05:47.815 [info] <0.278.0> 
 node           : rabbit@574f3bd8e872
 home dir       : /var/lib/rabbitmq
 config file(s) : /etc/rabbitmq/rabbitmq.conf
 cookie hash    : asxwuSQze84ld1Q3ynmmJg==
 log(s)         : <stdout>
 database dir   : /var/lib/rabbitmq/mnesia/rabbit@574f3bd8e872
2025-08-10 03:05:47.826 [info] <0.278.0> Running boot step pre_boot defined by app rabbit
2025-08-10 03:05:47.826 [info] <0.278.0> Running boot step rabbit_core_metrics defined by app rabbit
2025-08-10 03:05:47.826 [info] <0.278.0> Running boot step rabbit_alarm defined by app rabbit
2025-08-10 03:05:47.829 [info] <0.284.0> Memory high watermark set to 12815 MiB (13437547315 bytes) of 32037 MiB (33593868288 bytes) total
2025-08-10 03:05:47.831 [info] <0.286.0> Enabling free disk space monitoring
2025-08-10 03:05:47.831 [info] <0.286.0> Disk free limit set to 50MB
2025-08-10 03:05:47.832 [info] <0.278.0> Running boot step code_server_cache defined by app rabbit
2025-08-10 03:05:47.832 [info] <0.278.0> Running boot step file_handle_cache defined by app rabbit
2025-08-10 03:05:47.833 [info] <0.289.0> Limiting to approx 1048479 file handles (943629 sockets)
2025-08-10 03:05:47.833 [info] <0.290.0> FHC read buffering:  OFF
2025-08-10 03:05:47.833 [info] <0.290.0> FHC write buffering: ON
2025-08-10 03:05:47.833 [info] <0.278.0> Running boot step worker_pool defined by app rabbit
2025-08-10 03:05:47.833 [info] <0.279.0> Will use 16 processes for default worker pool
2025-08-10 03:05:47.833 [info] <0.279.0> Starting worker pool 'worker_pool' with 16 processes in it
2025-08-10 03:05:47.833 [info] <0.278.0> Running boot step database defined by app rabbit
2025-08-10 03:05:47.833 [info] <0.278.0> Node database directory at /var/lib/rabbitmq/mnesia/rabbit@574f3bd8e872 is empty. Assuming we need to join an existing cluster or initialise from scratch...
2025-08-10 03:05:47.833 [info] <0.278.0> Configured peer discovery backend: rabbit_peer_discovery_classic_config
2025-08-10 03:05:47.833 [info] <0.278.0> Will try to lock with peer discovery backend rabbit_peer_discovery_classic_config
2025-08-10 03:05:47.833 [info] <0.278.0> Peer discovery backend does not support locking, falling back to randomized delay
2025-08-10 03:05:47.834 [info] <0.278.0> Peer discovery backend rabbit_peer_discovery_classic_config does not support registration, skipping randomized startup delay.
2025-08-10 03:05:47.834 [info] <0.278.0> All discovered existing cluster peers: 
2025-08-10 03:05:47.834 [info] <0.278.0> Discovered no peer nodes to cluster with. Some discovery backends can filter nodes out based on a readiness criteria. Enabling debug logging might help troubleshoot.
2025-08-10 03:05:47.835 [info] <0.44.0> Application mnesia exited with reason: stopped
2025-08-10 03:05:47.869 [info] <0.278.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
2025-08-10 03:05:47.888 [info] <0.278.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
2025-08-10 03:05:47.888 [info] <0.278.0> Feature flag `drop_unroutable_metric`: supported, attempt to enable...
2025-08-10 03:05:47.888 [info] <0.278.0> Feature flag `drop_unroutable_metric`: mark as enabled=state_changing
2025-08-10 03:05:47.897 [info] <0.278.0> Feature flags: list of feature flags found:
2025-08-10 03:05:47.897 [info] <0.278.0> Feature flags:   [~] drop_unroutable_metric
2025-08-10 03:05:47.897 [info] <0.278.0> Feature flags:   [ ] empty_basic_get_metric
2025-08-10 03:05:47.897 [info] <0.278.0> Feature flags:   [ ] implicit_default_bindings
2025-08-10 03:05:47.897 [info] <0.278.0> Feature flags:   [ ] quorum_queue
2025-08-10 03:05:47.897 [info] <0.278.0> Feature flags:   [ ] virtual_host_metadata
2025-08-10 03:05:47.897 [info] <0.278.0> Feature flags: feature flag states written to disk: yes
2025-08-10 03:05:47.903 [info] <0.278.0> Feature flag `drop_unroutable_metric`: mark as enabled=true
2025-08-10 03:05:47.913 [info] <0.278.0> Feature flags: list of feature flags found:
2025-08-10 03:05:47.913 [info] <0.278.0> Feature flags:   [x] drop_unroutable_metric
2025-08-10 03:05:47.913 [info] <0.278.0> Feature flags:   [ ] empty_basic_get_metric
2025-08-10 03:05:47.913 [info] <0.278.0> Feature flags:   [ ] implicit_default_bindings
2025-08-10 03:05:47.913 [info] <0.278.0> Feature flags:   [ ] quorum_queue
2025-08-10 03:05:47.913 [info] <0.278.0> Feature flags:   [ ] virtual_host_metadata
2025-08-10 03:05:47.913 [info] <0.278.0> Feature flags: feature flag states written to disk: yes
2025-08-10 03:05:47.919 [info] <0.278.0> Feature flag `empty_basic_get_metric`: supported, attempt to enable...
2025-08-10 03:05:47.919 [info] <0.278.0> Feature flag `empty_basic_get_metric`: mark as enabled=state_changing
2025-08-10 03:05:47.929 [info] <0.278.0> Feature flags: list of feature flags found:
2025-08-10 03:05:47.929 [info] <0.278.0> Feature flags:   [x] drop_unroutable_metric
2025-08-10 03:05:47.929 [info] <0.278.0> Feature flags:   [~] empty_basic_get_metric
2025-08-10 03:05:47.929 [info] <0.278.0> Feature flags:   [ ] implicit_default_bindings
2025-08-10 03:05:47.929 [info] <0.278.0> Feature flags:   [ ] quorum_queue
2025-08-10 03:05:47.929 [info] <0.278.0> Feature flags:   [ ] virtual_host_metadata
2025-08-10 03:05:47.929 [info] <0.278.0> Feature flags: feature flag states written to disk: yes
2025-08-10 03:05:47.936 [info] <0.278.0> Feature flag `empty_basic_get_metric`: mark as enabled=true
2025-08-10 03:05:47.945 [info] <0.278.0> Feature flags: list of feature flags found:
2025-08-10 03:05:47.945 [info] <0.278.0> Feature flags:   [x] drop_unroutable_metric
2025-08-10 03:05:47.945 [info] <0.278.0> Feature flags:   [x] empty_basic_get_metric
2025-08-10 03:05:47.945 [info] <0.278.0> Feature flags:   [ ] implicit_default_bindings
2025-08-10 03:05:47.945 [info] <0.278.0> Feature flags:   [ ] quorum_queue
2025-08-10 03:05:47.945 [info] <0.278.0> Feature flags:   [ ] virtual_host_metadata
2025-08-10 03:05:47.945 [info] <0.278.0> Feature flags: feature flag states written to disk: yes
2025-08-10 03:05:47.951 [info] <0.278.0> Feature flag `implicit_default_bindings`: supported, attempt to enable...
2025-08-10 03:05:47.951 [info] <0.278.0> Feature flag `implicit_default_bindings`: mark as enabled=state_changing
2025-08-10 03:05:47.960 [info] <0.278.0> Feature flags: list of feature flags found:
2025-08-10 03:05:47.960 [info] <0.278.0> Feature flags:   [x] drop_unroutable_metric
2025-08-10 03:05:47.960 [info] <0.278.0> Feature flags:   [x] empty_basic_get_metric
2025-08-10 03:05:47.961 [info] <0.278.0> Feature flags:   [~] implicit_default_bindings
2025-08-10 03:05:47.961 [info] <0.278.0> Feature flags:   [ ] quorum_queue
2025-08-10 03:05:47.961 [info] <0.278.0> Feature flags:   [ ] virtual_host_metadata
2025-08-10 03:05:47.961 [info] <0.278.0> Feature flags: feature flag states written to disk: yes
2025-08-10 03:05:47.967 [info] <0.278.0> Waiting for Mnesia tables for 30000 ms, 0 retries left
2025-08-10 03:05:47.967 [info] <0.278.0> Feature flag `implicit_default_bindings`: mark as enabled=true
2025-08-10 03:05:47.977 [info] <0.278.0> Feature flags: list of feature flags found:
2025-08-10 03:05:47.977 [info] <0.278.0> Feature flags:   [x] drop_unroutable_metric
2025-08-10 03:05:47.977 [info] <0.278.0> Feature flags:   [x] empty_basic_get_metric
2025-08-10 03:05:47.977 [info] <0.278.0> Feature flags:   [x] implicit_default_bindings
2025-08-10 03:05:47.977 [info] <0.278.0> Feature flags:   [ ] quorum_queue
2025-08-10 03:05:47.977 [info] <0.278.0> Feature flags:   [ ] virtual_host_metadata
2025-08-10 03:05:47.977 [info] <0.278.0> Feature flags: feature flag states written to disk: yes
2025-08-10 03:05:47.983 [info] <0.278.0> Feature flag `quorum_queue`: supported, attempt to enable...
2025-08-10 03:05:47.983 [info] <0.278.0> Feature flag `quorum_queue`: mark as enabled=state_changing
2025-08-10 03:05:47.992 [info] <0.278.0> Feature flags: list of feature flags found:
2025-08-10 03:05:47.992 [info] <0.278.0> Feature flags:   [x] drop_unroutable_metric
2025-08-10 03:05:47.992 [info] <0.278.0> Feature flags:   [x] empty_basic_get_metric
2025-08-10 03:05:47.992 [info] <0.278.0> Feature flags:   [x] implicit_default_bindings
2025-08-10 03:05:47.992 [info] <0.278.0> Feature flags:   [~] quorum_queue
2025-08-10 03:05:47.992 [info] <0.278.0> Feature flags:   [ ] virtual_host_metadata
2025-08-10 03:05:47.992 [info] <0.278.0> Feature flags: feature flag states written to disk: yes
2025-08-10 03:05:47.999 [info] <0.278.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
2025-08-10 03:05:47.999 [info] <0.278.0> Feature flag `quorum_queue`:   migrating Mnesia table rabbit_queue...
2025-08-10 03:05:48.004 [info] <0.278.0> Feature flag `quorum_queue`:   migrating Mnesia table rabbit_durable_queue...
2025-08-10 03:05:48.009 [info] <0.278.0> Feature flag `quorum_queue`:   Mnesia tables migration done
2025-08-10 03:05:48.009 [info] <0.278.0> Feature flag `quorum_queue`: mark as enabled=true
2025-08-10 03:05:48.019 [info] <0.278.0> Feature flags: list of feature flags found:
2025-08-10 03:05:48.019 [info] <0.278.0> Feature flags:   [x] drop_unroutable_metric
2025-08-10 03:05:48.019 [info] <0.278.0> Feature flags:   [x] empty_basic_get_metric
2025-08-10 03:05:48.019 [info] <0.278.0> Feature flags:   [x] implicit_default_bindings
2025-08-10 03:05:48.019 [info] <0.278.0> Feature flags:   [x] quorum_queue
2025-08-10 03:05:48.019 [info] <0.278.0> Feature flags:   [ ] virtual_host_metadata
2025-08-10 03:05:48.019 [info] <0.278.0> Feature flags: feature flag states written to disk: yes
2025-08-10 03:05:48.025 [info] <0.278.0> Feature flag `virtual_host_metadata`: supported, attempt to enable...
2025-08-10 03:05:48.025 [info] <0.278.0> Feature flag `virtual_host_metadata`: mark as enabled=state_changing
2025-08-10 03:05:48.035 [info] <0.278.0> Feature flags: list of feature flags found:
2025-08-10 03:05:48.036 [info] <0.278.0> Feature flags:   [x] drop_unroutable_metric
2025-08-10 03:05:48.036 [info] <0.278.0> Feature flags:   [x] empty_basic_get_metric
2025-08-10 03:05:48.036 [info] <0.278.0> Feature flags:   [x] implicit_default_bindings
2025-08-10 03:05:48.036 [info] <0.278.0> Feature flags:   [x] quorum_queue
2025-08-10 03:05:48.036 [info] <0.278.0> Feature flags:   [~] virtual_host_metadata
2025-08-10 03:05:48.036 [info] <0.278.0> Feature flags: feature flag states written to disk: yes
2025-08-10 03:05:48.042 [info] <0.278.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
2025-08-10 03:05:48.047 [info] <0.278.0> Feature flag `virtual_host_metadata`: mark as enabled=true
2025-08-10 03:05:48.057 [info] <0.278.0> Feature flags: list of feature flags found:
2025-08-10 03:05:48.057 [info] <0.278.0> Feature flags:   [x] drop_unroutable_metric
2025-08-10 03:05:48.057 [info] <0.278.0> Feature flags:   [x] empty_basic_get_metric
2025-08-10 03:05:48.057 [info] <0.278.0> Feature flags:   [x] implicit_default_bindings
2025-08-10 03:05:48.057 [info] <0.278.0> Feature flags:   [x] quorum_queue
2025-08-10 03:05:48.057 [info] <0.278.0> Feature flags:   [x] virtual_host_metadata
2025-08-10 03:05:48.057 [info] <0.278.0> Feature flags: feature flag states written to disk: yes
2025-08-10 03:05:48.063 [info] <0.278.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
2025-08-10 03:05:48.084 [info] <0.278.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
2025-08-10 03:05:48.084 [info] <0.278.0> Peer discovery backend rabbit_peer_discovery_classic_config does not support registration, skipping registration.
2025-08-10 03:05:48.084 [info] <0.278.0> Running boot step database_sync defined by app rabbit
2025-08-10 03:05:48.084 [info] <0.278.0> Running boot step feature_flags defined by app rabbit
2025-08-10 03:05:48.084 [info] <0.278.0> Running boot step codec_correctness_check defined by app rabbit
2025-08-10 03:05:48.084 [info] <0.278.0> Running boot step external_infrastructure defined by app rabbit
2025-08-10 03:05:48.084 [info] <0.278.0> Running boot step rabbit_registry defined by app rabbit
2025-08-10 03:05:48.084 [info] <0.278.0> Running boot step rabbit_auth_mechanism_cr_demo defined by app rabbit
2025-08-10 03:05:48.084 [info] <0.278.0> Running boot step rabbit_queue_location_random defined by app rabbit
2025-08-10 03:05:48.084 [info] <0.278.0> Running boot step rabbit_event defined by app rabbit
2025-08-10 03:05:48.084 [info] <0.278.0> Running boot step rabbit_auth_mechanism_amqplain defined by app rabbit
2025-08-10 03:05:48.084 [info] <0.278.0> Running boot step rabbit_auth_mechanism_plain defined by app rabbit
2025-08-10 03:05:48.084 [info] <0.278.0> Running boot step rabbit_exchange_type_direct defined by app rabbit
2025-08-10 03:05:48.084 [info] <0.278.0> Running boot step rabbit_exchange_type_fanout defined by app rabbit
2025-08-10 03:05:48.084 [info] <0.278.0> Running boot step rabbit_exchange_type_headers defined by app rabbit
2025-08-10 03:05:48.084 [info] <0.278.0> Running boot step rabbit_exchange_type_topic defined by app rabbit
2025-08-10 03:05:48.085 [info] <0.278.0> Running boot step rabbit_mirror_queue_mode_all defined by app rabbit
2025-08-10 03:05:48.085 [info] <0.278.0> Running boot step rabbit_mirror_queue_mode_exactly defined by app rabbit
2025-08-10 03:05:48.085 [info] <0.278.0> Running boot step rabbit_mirror_queue_mode_nodes defined by app rabbit
2025-08-10 03:05:48.085 [info] <0.278.0> Running boot step rabbit_priority_queue defined by app rabbit
2025-08-10 03:05:48.085 [info] <0.278.0> Priority queues enabled, real BQ is rabbit_variable_queue
2025-08-10 03:05:48.085 [info] <0.278.0> Running boot step rabbit_queue_location_client_local defined by app rabbit
2025-08-10 03:05:48.085 [info] <0.278.0> Running boot step rabbit_queue_location_min_masters defined by app rabbit
2025-08-10 03:05:48.085 [info] <0.278.0> Running boot step kernel_ready defined by app rabbit
2025-08-10 03:05:48.085 [info] <0.278.0> Running boot step rabbit_sysmon_minder defined by app rabbit
2025-08-10 03:05:48.085 [info] <0.278.0> Running boot step rabbit_epmd_monitor defined by app rabbit
2025-08-10 03:05:48.086 [info] <0.532.0> epmd monitor knows us, inter-node communication (distribution) port: 25672
2025-08-10 03:05:48.086 [info] <0.278.0> Running boot step guid_generator defined by app rabbit
2025-08-10 03:05:48.088 [info] <0.278.0> Running boot step rabbit_node_monitor defined by app rabbit
2025-08-10 03:05:48.088 [info] <0.538.0> Starting rabbit_node_monitor
2025-08-10 03:05:48.088 [info] <0.278.0> Running boot step delegate_sup defined by app rabbit
2025-08-10 03:05:48.088 [info] <0.278.0> Running boot step rabbit_memory_monitor defined by app rabbit
2025-08-10 03:05:48.088 [info] <0.278.0> Running boot step core_initialized defined by app rabbit
2025-08-10 03:05:48.088 [info] <0.278.0> Running boot step upgrade_queues defined by app rabbit
2025-08-10 03:05:48.107 [info] <0.278.0> message_store upgrades: 1 to apply
2025-08-10 03:05:48.107 [info] <0.278.0> message_store upgrades: Applying rabbit_variable_queue:move_messages_to_vhost_store
2025-08-10 03:05:48.107 [info] <0.278.0> message_store upgrades: No durable queues found. Skipping message store migration
2025-08-10 03:05:48.107 [info] <0.278.0> message_store upgrades: Removing the old message store data
2025-08-10 03:05:48.108 [info] <0.278.0> message_store upgrades: All upgrades applied successfully
2025-08-10 03:05:48.126 [info] <0.278.0> Running boot step rabbit_connection_tracking defined by app rabbit
2025-08-10 03:05:48.126 [info] <0.278.0> Running boot step rabbit_connection_tracking_handler defined by app rabbit
2025-08-10 03:05:48.126 [info] <0.278.0> Running boot step rabbit_exchange_parameters defined by app rabbit
2025-08-10 03:05:48.127 [info] <0.278.0> Running boot step rabbit_mirror_queue_misc defined by app rabbit
2025-08-10 03:05:48.127 [info] <0.278.0> Running boot step rabbit_policies defined by app rabbit
2025-08-10 03:05:48.128 [info] <0.278.0> Running boot step rabbit_policy defined by app rabbit
2025-08-10 03:05:48.128 [info] <0.278.0> Running boot step rabbit_queue_location_validator defined by app rabbit
2025-08-10 03:05:48.128 [info] <0.278.0> Running boot step rabbit_quorum_memory_manager defined by app rabbit
2025-08-10 03:05:48.128 [info] <0.278.0> Running boot step rabbit_vhost_limit defined by app rabbit
2025-08-10 03:05:48.128 [info] <0.278.0> Running boot step rabbit_mgmt_reset_handler defined by app rabbitmq_management
2025-08-10 03:05:48.128 [info] <0.278.0> Running boot step rabbit_mgmt_db_handler defined by app rabbitmq_management_agent
2025-08-10 03:05:48.128 [info] <0.278.0> Management plugin: using rates mode 'basic'
2025-08-10 03:05:48.128 [info] <0.278.0> Running boot step recovery defined by app rabbit
2025-08-10 03:05:48.129 [info] <0.278.0> Running boot step load_core_definitions defined by app rabbit
2025-08-10 03:05:48.129 [info] <0.278.0> Running boot step empty_db_check defined by app rabbit
2025-08-10 03:05:48.129 [info] <0.278.0> Adding vhost '/' (description: 'Default virtual host')
2025-08-10 03:05:48.135 [info] <0.579.0> Making sure data directory '/var/lib/rabbitmq/mnesia/rabbit@574f3bd8e872/msg_stores/vhosts/628WB79CIFDYO9LJI6DKMI09L' for vhost '/' exists
2025-08-10 03:05:48.137 [info] <0.579.0> Starting message stores for vhost '/'
2025-08-10 03:05:48.137 [info] <0.583.0> Message store "628WB79CIFDYO9LJI6DKMI09L/msg_store_transient": using rabbit_msg_store_ets_index to provide index
2025-08-10 03:05:48.138 [info] <0.579.0> Started message store of type transient for vhost '/'
2025-08-10 03:05:48.138 [info] <0.586.0> Message store "628WB79CIFDYO9LJI6DKMI09L/msg_store_persistent": using rabbit_msg_store_ets_index to provide index
2025-08-10 03:05:48.138 [warning] <0.586.0> Message store "628WB79CIFDYO9LJI6DKMI09L/msg_store_persistent": rebuilding indices from scratch
2025-08-10 03:05:48.138 [info] <0.579.0> Started message store of type persistent for vhost '/'
2025-08-10 03:05:48.139 [info] <0.278.0> Creating user 'coinscrap'
2025-08-10 03:05:48.140 [info] <0.278.0> Setting user tags for user 'coinscrap' to [administrator]
2025-08-10 03:05:48.141 [info] <0.278.0> Setting permissions for 'coinscrap' in '/' to '.*', '.*', '.*'
2025-08-10 03:05:48.141 [info] <0.278.0> Running boot step rabbit_looking_glass defined by app rabbit
2025-08-10 03:05:48.141 [info] <0.278.0> Running boot step rabbit_core_metrics_gc defined by app rabbit
2025-08-10 03:05:48.142 [info] <0.278.0> Running boot step background_gc defined by app rabbit
2025-08-10 03:05:48.142 [info] <0.278.0> Running boot step connection_tracking defined by app rabbit
2025-08-10 03:05:48.143 [info] <0.278.0> Setting up a table for connection tracking on this node: tracked_connection_on_node_rabbit@574f3bd8e872
2025-08-10 03:05:48.144 [info] <0.278.0> Setting up a table for per-vhost connection counting on this node: tracked_connection_per_vhost_on_node_rabbit@574f3bd8e872
2025-08-10 03:05:48.145 [info] <0.278.0> Running boot step routing_ready defined by app rabbit
2025-08-10 03:05:48.145 [info] <0.278.0> Running boot step pre_flight defined by app rabbit
2025-08-10 03:05:48.145 [info] <0.278.0> Running boot step notify_cluster defined by app rabbit
2025-08-10 03:05:48.145 [info] <0.278.0> Running boot step networking defined by app rabbit
2025-08-10 03:05:48.146 [info] <0.632.0> started TCP listener on [::]:5672
2025-08-10 03:05:48.146 [info] <0.278.0> Running boot step cluster_name defined by app rabbit
2025-08-10 03:05:48.146 [info] <0.278.0> Initialising internal cluster ID to 'rabbitmq-cluster-id-7RCn58xDlB_qBWMMNErkGg'
2025-08-10 03:05:48.147 [info] <0.278.0> Running boot step direct_client defined by app rabbit
2025-08-10 03:05:48.147 [info] <0.278.0> Running boot step os_signal_handler defined by app rabbit
2025-08-10 03:05:48.147 [info] <0.635.0> Swapping OS signal event handler (erl_signal_server) for our own
2025-08-10 03:05:48.169 [info] <0.685.0> Management plugin: HTTP (non-TLS) listener started on port 15672
2025-08-10 03:05:48.169 [info] <0.791.0> Statistics database started.
2025-08-10 03:05:48.169 [info] <0.790.0> Starting worker pool 'management_worker_pool' with 3 processes in it
2025-08-10 03:05:48.255 [info] <0.9.0> Server startup complete; 3 plugins started.
 * rabbitmq_management
 * rabbitmq_management_agent
 * rabbitmq_web_dispatch
 completed with 3 plugins.

//Here is the initial conection of my service starts

2025-08-10 03:06:52.566 [info] <0.916.0> accepting AMQP connection <0.916.0> (172.17.0.1:54466 -> 172.17.0.2:5672)
2025-08-10 03:06:52.611 [info] <0.916.0> connection <0.916.0> (172.17.0.1:54466 -> 172.17.0.2:5672): user 'coinscrap' authenticated and granted access to vhost '/'


//My service publishes and reads a mesage (server does not log this ones)
// Then my service just shutdowns


//No more logs, no shutdown/disconect tries from client
