### ISSUE TITLE
Persistent flag and performance Issues

### ISSUE THREAD

**Issue by willthrom** [guidesmiths/rascal#115] opened 2020-08-10 15:12 UTC
Coming from ampqlib with message persistence, the performance drop by 3.
We have configured a pool of 3 channels (tested with 10 as well) with confirmed channels.

Direct Ampqlib returns 1200 msg/s publish, with only one service (3 channels), but when moving to Rascal the performance drops to 350 msg/s.

If we disable persistence, then the result of publishing are very similar, around 133-1500 msg/s

We cannot find the problem but we checked Rascal Library and it seems the flag for "persistence" doesn't have any treatment. it is just forwarded to the ampqlib and then to the message.

Any clue?  Both libraries are tested with the same simulator, and same HW. We cannot find the different between using these libraries.   We might be missing something.....

**Comment by cressie176** [comment] 2020-08-10 19:26
Thanks for reporting. I'll see if I can reproduce and work out what's going on.

**Comment by willthrom** [comment] 2020-08-10 21:02
> Thanks for reporting. I'll see if I can reproduce and work out what's going on.

Thanks, I am pretty sure it has nothing to do with the Rascal but I am quite lost because it is working fine without using the flag so I cannot tell where and how.  

ConfirmChannel is part of ampqLib and it is only a property in the message itself. Cannot tell yet what rabbitMQ 3.6 is doing at their end (No replication enabled).

**Comment by cressie176** [comment] 2020-08-10 21:26
I can quite imagine Rascal will be slower, due to the channel pool and extra layers of code. I added a few `console.time` statements and published a single message...

```
broker publish: 1.444ms
borrow channel: 3.331ms
publishFn: 7.880ms
  sendToQueue: 7.388ms
    amqplib sendToQueue: 7.223ms
tidy up: 0.289ms
rascal: 12.711ms
```
The additional rascal layers add about ~5ms, with borrowing a channel adds ~3ms per publish, and this is after waiting a few seconds for the channel pool to be initialised.

However this isn't enough to explain why rascal takes 3x as long. One possible reason is that Rascal does not take advantage of channel multiplexing (the ability to publish messages concurrently to a channel). Instead it will only return a confirm channel to the pool once the acknowledgement has been received. With persistent messages, this means waiting until the message as been written to disk.

Depending on how you've written your direct amqplib test code, if you are not waiting to receive the confirmation before publishing another message to the same channel, this would explain why the amqplib code is significantly faster.

**Comment by cressie176** [comment] 2020-08-10 21:33
There's another subtle difference which accounts for a few more milliseconds (~7)...

The following code is slower than code which does not use `ok`
```js
      const ok = channel.sendToQueue('queue', Buffer.from('Hello World!'), {
        persistent: true,
        mandatory: true,
      }, function(err) {
        console.timeEnd('amqplib');
        console.log(ok);
        process.exit();
      })
```

Rascal uses `ok` to detect saturated channels. If your amqplib test code does not do something similar it will have an advantage.

I'd actually commented this out in my previous response which included the timings, but when I re-enabled it, they got significantly slower...
```
broker publish: 1.480ms
borrow channel: 3.715ms
publishFn: 14.587ms
  sendToQueue: 14.454ms
    amqplib sendToQueue: 14.314ms
tidy up: 0.341ms
rascal: 19.764ms
```

**Comment by willthrom** [comment] 2020-08-10 21:36
With ampqlib what we did was to create as many channel as we want and just use round robin or based on a key in the message (I would need to check).   

I did the test with 200K message for your info.

What you mention about multiplexing might be the reason as what we do is each "publish" promise will wait for the confirmation of the channel to confirm the request (Rest API), but it doesn't stop us to do multiple publish wait for the same channel. We use Publish, no sentToQueue.

I mean:  Rest/Api Endpoint (Send Message) -> Choose Channel based on Key -> Publish -> Wait for confirmation -> HTTP Response.

I simulated the Rest/Api with K6 (Simulator), but only using 30-50 connections to the Endpoints.

I might try tomorrow 30 Connections from K6 to our service but 30 channels from Rascal... But it might be an option to support multiplexing the channels.. at end of the day it is implemented in ampqlib....

**Comment by willthrom** [comment] 2020-08-10 21:37
And another thing....  

I could understand all the delays because the extra layer but not when it is only drastic when persistence is enable.

**Comment by willthrom** [comment] 2020-08-10 21:39
![image](https://user-images.githubusercontent.com/2103849/89834207-45a1e980-db5a-11ea-8ea1-70c967133b2e.png)

**Comment by willthrom** [comment] 2020-08-10 21:45
**ampqLib Version:**
`const publish = async (ex, k, b) => {
  return new Promise(async (resolve, reject) => {
    
    
    logger.debug("********************************************************************************************************************")
    logger.debug("********************************************************************************************************************")
    var idx 
    idx = parseInt(b.id) % NUM_CHANNELS
    if (idx!=idx) { // NAN
      idx=Math.floor(Math.random() * NUM_CHANNELS);
    }
    logger.debug(" ID " + b.id)
    logger.debug(" Index " + idx)
    try {   
      await channels[idx].publish(ex, k, new Buffer.from(JSON.stringify(b)), { persistent: true })
      await channels[idx].waitForConfirms()  
      logger.debug({ ex, k, b }, 'Message published to queue')
      return resolve()
    } catch (e) {
      return reject({
        message: 'RabbitMQ publish failed',
        details: e.toString()
      })
    }
  })
}
`

**Rascal Version**
`const publish = async (p, m) => {
  try {
    const publication = await broker.publish(p, m)
    return new Promise((resolve, reject) => {
      publication
        .on('success', id => {
          logger.info(`Message successfully published with id [${id}]: ${m}`)
          resolve(e)
        })
        .on('error', e => {
          reject(e)
        })
        .on('return', msg => {
          logger.warn('Message was returned: ' + JSON.stringify(msg))
          resolve()
        })
    }) 
  } catch (e) {
    logger.error('Error publishing message: ' + (e.message || e.toString() || e))
  }
}
`

**Comment by cressie176** [comment] 2020-08-10 21:48
> We use Publish, no sentToQueue.

Thanks for pointing this out, but I don't think this will make any difference - channel.sendToQueue gets translated to channel.publish in amqplib - the message is sent to the default exchange and routed to the queue using the queue name as the routing key 

> What you mention about multiplexing might be the reason as what we do is each "publish" promise will wait for the confirmation of the channel to confirm the request (Rest API), but it doesn't stop us to do multiple publish wait for the same channel.

This is very likely to be the cause

> But it might be an option to support multiplexing the channels.. at end of the day it is implemented in ampqlib....

When I designed Rascal, I deliberately avoided multiplexing channels, because if a channel error occurs, it would affect all current "publishers" to the channel. I'm less sure this is an issue now, as there aren't many things that can go wrong with a channel when publishing messages.

**Comment by willthrom** [comment] 2020-08-10 21:53
> When I designed Rascal, I deliberately avoided multiplexing channels, because if a channel error occurs, it would affect all current "publishers" to the channel. I'm less sure this is an issue now, as there aren't many things that can go wrong with a channel when publishing messages.

For this we have the events of OnError, so we just reconnect the channels, basic stuff.
Our main problem with ampqlib is the lack of support of Cluster, and we saw in Rascal a very good option to avoid to have to implement it ourselves plus it looks much better that other options our there ( plus Rascal Documentation is extremely good)

**Comment by cressie176** [comment] 2020-08-10 21:54
A couple of observations with the above...

The amqplib example will publish messages to the same channel, which explains why it's so much faster. You can increase the rascal's `max` channels significantly and you should see an improvement, but it's still not likely to hit the same performance as multiplexing.

```
await channels[idx].publish(ex, k, new Buffer.from(JSON.stringify(b)), { persistent: true })
```

channel.publish does not return a promise, and therefore does not need to be awaited. Instead it synchronously returns a boolean indicating whether the channel buffer is full. You can continue writing to the buffer even if it is full however.

```
        .on('success', id => {
          logger.info(`Message successfully published with id [${id}]: ${m}`)
          resolve(e)
        })
        .on('error', e => {
          reject(e)
        })
        .on('return', msg => {
          logger.warn('Message was returned: ' + JSON.stringify(msg))
          resolve()
        })
```

There's an error in the success handler - `resolve(e)` - e is not defined. Assume this is just a typo transcribing your code into the github issue.

If you get a `return` you should have previously received a `success`, so resolving from the return is pointless.



(I better check the rascal code to be sure this wasn't from an example!)

**Comment by cressie176** [comment] 2020-08-10 21:59
> For this we have the events of OnError, so we just reconnect the channels, basic stuff.

Multiple publishes, rather than one would still fail though. Initially Rascal opened/closed a new channel for each publish to avoid this, but it was even slower. We added the channel pool as a way of improving the speed, but as I said earlier, I don't think there's much chance of a channel error being caused by anything other than a connection error when publishing, so I'm not sure whether the dedicated channel per publish or channel pools were really that worthwhile.

If I'm right, and it isn't worthwhile, then I'm willing to remove the pooling (it's always been a pain to manage), but it's not likely to happen anytime soon.

**Comment by willthrom** [comment] 2020-08-10 22:03
> A couple of observations with the above...
> 
> The amqplib example will publish messages to the same channel, which explains why it's so much faster. You can increase the rascal's `max` channels significantly and you should see an improvement, but it's still not likely to hit the same performance as multiplexing.
> 
> ```
> await channels[idx].publish(ex, k, new Buffer.from(JSON.stringify(b)), { persistent: true })
> ```
> 
> channel.publish does not return a promise, and therefore does not need to be awaited. Instead it synchronously returns a boolean indicating whether the channel buffer is full. You can continue writing to the buffer even if it is full however.


According to the ampqLib plublish can return a promise of a callback
http://www.squaremobius.net/amqp.node/channel_api.html?spm=a2c6h.14275010.0.0.51ff3d6as11bDp#channel_publish

In any case, we use the await channels[idx].waitForConfirms() 

> 
> ```
>         .on('success', id => {
>           logger.info(`Message successfully published with id [${id}]: ${m}`)
>           resolve(e)
>         })
>         .on('error', e => {
>           reject(e)
>         })
>         .on('return', msg => {
>           logger.warn('Message was returned: ' + JSON.stringify(msg))
>           resolve()
>         })
> ```
> 
> There's an error in the success handler - `resolve(e)` - e is not defined. Assume this is just a typo transcribing your code into the github issue.
> 
> If you get a `return` you should have previously received a `success`, so resolving from the return is pointless.
> 
> (I better check the rascal code to be sure this wasn't from an example!)

oh, I will check that with the developer. Thanks".. 
`resolve(e)` on it an error but.. weird we didn't see any issue after several runs of 200K dataset..

**Comment by willthrom** [comment] 2020-08-10 22:06
> > For this we have the events of OnError, so we just reconnect the channels, basic stuff.
> 
> Multiplexed publishes would still result in multiple failures if the channel errored though. Initially Rascal opened/closed a new channel for each publish to avoid this, but it was even slower. We added the channel pool as a way of improving the speed, but as I said earlier, I don't think there's much chance of a channel error being caused by anything other than a connection error when publishing, and this would also affect all inflight publishes, so I'm not sure whether the dedicated channel per publish or channel pools were really that worthwhile.
> 
> If I'm right, and it isn't worthwhile, then I'm willing to remove the pooling (it's always been a pain to manage), but it's not likely to happen anytime soon.

I might take a fork and change the pooling for our "low quality" implementation of Key Based channel selection :)

But I need to find first if that is the reason... as you can see in my previous post,   the number between Persistense on and off are too drastic to be only because channel... well.. let me think about that, because maybe the waiting it too much ( Quite late here to keep thinking about this)

**Comment by willthrom** [comment] 2020-08-11 08:54
Hi,

I did some more test playing with the number of channels, and yes, increasing from 3 (amqlib) to 30 channels, the performance improves. Not at the same level, but similar. Enabling replication makes it looks bad again, so adding more channels seems to "fix" the problem, 50.

So, if I find the time, I might do a fork and add the option of multiplexing (basic round-robin) in your channel pool.

My current target is 1000 msg/s with replication and with Rascal we are far from that, unfortunately.

**Comment by cressie176** [comment] 2020-08-11 09:07
> So, if I find the time, I might do a fork and add the option of multiplexing (basic round-robin) in your channel pool.

Out of interest, do you notice any performance improvement when multiplexing using a single channel vs using multiple (also multiplexed) channels? Given node has only 1 user thread, and assuming channels shared a connection, I'm curious whether there's an advantage in having multiple channels when multiplexing. I'm thinking of replacing Rascal's pooling with either a shared pool of normal/confirme channels as per your round-robin example, or event just one normal channel and one confirm channel.

> My current target is 1000 msg/s with replication and with Rascal we are far from that, unfortunately.

Replication with RabbitMQ is known to be slow (compared to not replicating), and the more nodes you replicate to the slower it gets unfortunately. It also doesn't handle network partitions very gracefully. RabbitMQ 3.8.x introduced quorum queues, which look much better, but have some limitations (e.g. messages cannot be mandatory), so might be worth investigating.

**Comment by willthrom** [comment] 2020-08-11 09:34
> > So, if I find the time, I might do a fork and add the option of multiplexing (basic round-robin) in your channel pool.
> 
> Out of interest, do you notice any performance improvement when multiplexing using a single channel vs using multiple (also multiplexed) channels? Given node has only 1 user thread, and assuming channels shared a connection, I'm curious whether there's an advantage in having multiple channels when multiplexing. I'm thinking of replacing Rascal's pooling with either a shared pool of normal/confirme channels as per your round-robin example, or event just one normal channel and one confirm channel.
> 

For my specific scenario, 1 channel or 3 makes a different, but not bigger number of channels than that. Will look for the simulation results I got and let you know.


> > My current target is 1000 msg/s with replication and with Rascal we are far from that, unfortunately.
> 
> Replication with RabbitMQ is known to be slow (compared to not replicating), and the more nodes you replicate to the slower it gets unfortunately. It also doesn't handle network partitions very gracefully. RabbitMQ 3.8.x introduced quorum queues, which look much better, but are still slower and have other limitations (e.g. messages cannot be mandatory), so might be worth investigating.

I am aware of  Quorum Queues but we cannot update for the time being to 3.8 (in one of our deployments they don't want to touch RabbitMQ).

With the classic Replication I can disable persistence and "accept" the replication as "enough", I get 1000msg/s with replicating to one node, so my target is fulfil.

With the Quorum Queue, using RAF protocol, I cannot disable persistence, but I need to spend more time investigating.

**Comment by willthrom** [comment] 2020-08-11 09:37
![image](https://user-images.githubusercontent.com/2103849/89882381-a82cd100-dbbe-11ea-8b21-4e3ea890a4b7.png)

**Closed** 2020-08-18 09:26 UTC
