### ISSUE TITLE
Connection configuration inconsistency

### ISSUE THREAD

**Issue by Stene3** [guidesmiths/rascal#87] opened 2020-03-29 08:12 UTC
Hello,
thanks for providing great tool! While I'm using it for a short period, I found out some inconsistency between README and the current implementation in Connection configuration.

1. Regarding the README which tells me to simply provide connection as a string, connection attribute is of type `ConnectionConfig` only, not the string itself.

```
{
  "vhosts": {
    "v1": {
      // this won't work, string is not applicable for ConnectionConfig
      "connection": "amqp://guest:guest@broker.example.com:5672/v1?heartbeat=10"
    }
  }
}
```

2. Ok, so I tried with the `url` attribute inside the `ConnectionConfig`, which does not work either for me in combination with `withDefaultConfig`

```
{
  "vhosts": {
    "v1": {
      "connection": {
        // this is fine, but seems like to be ignored or overridden
        "url": "amqp://guest:guest@broker.example.com:5672/v1?heartbeat=10"
      }
    }
  }
}
```

This ends up in a connection issue: `Failed to check vhost: /. http://guest:***@localhost:15672 errored with: connect ECONNREFUSED 127.0.0.1:15672`.

Seems like my url is being overridden be a default value. I'm not able to configure connection using a string. Only working solution seems to be to pass an object with `username`, `password`, `hostname` attributes supplied.

----

UPDATE: I've realized the problem number 2 is caused by `check: true` in the vhost configuration, which is using management API to validate this. I've completely missed that port difference in the log. So right now url attribute of the `ConnectionConfig` object is used.

There's only a Typo in the README, the point 1 is valid :-)

**Comment by cressie176** [comment] 2020-03-29 12:03
Hi @Stene3,

Thanks for reporting. The way rascal currently manages defaults is due for an overhaul and can [lead to problems](https://github.com/guidesmiths/rascal/issues/78) if you don't either: 

  (a) use `Rascal.withDefaultConfig(config)`, or 
  (b) specify all the necessary defaults (unfortunately, not well documented). 

However, I wasn't able to reproduce the same problems you are facing...

### Test Code
```
var Rascal = require('rascal')
var config = require('./config');
Rascal.Broker.create(Rascal.withDefaultConfig(config), function(err, broker) {
  if (err) throw err
  console.log('Started OK');
})
```
### Test 1 (string connection attribute)
#### Config
```json
{
  "vhosts": {
    "v1": {
      "connection": "amqp://guest:guest@localhost:5672/v1?heartbeat=10"
    }
  }
}
```
#### Result 
```
Started OK
```

### Test 2 (url connection attribute)
#### Config
```json
{
  "vhosts": {
    "v1": {
      "connection": {
        "url": "amqp://guest:guest@localhost:5672/v1?heartbeat=10"
      }
    }
  }
}
```

When I tried changing localhost to `broker.example.com`, in both examples the connection was refused, indicating that the configuration was overriding the defaults as expected.

My advice for the moment is to base off the default configuration via `Rascal.withDefaultConfig(config)` until I've had a chance to rework things.

**Comment by cressie176** [comment] 2020-04-07 20:48
I'm going to close this as a (non obvious) duplicate of https://github.com/guidesmiths/rascal/issues/78. Still not quite sure what I'm going to do with the default config yet though.

**Closed by cressie176** 2020-04-07 20:48 UTC
